title: HPC Basics
lang: en
description: Documentation home for HPC Basics instruction

remote_theme: rundocs/jekyll-rtd-theme
#theme: null

nav_version: true
edit: true
addons_branch: true

addons:
  - github
  - i18n
  - plugins
  - analytics

copyright:
  revision: true

readme_index:
  with_frontmatter: true

sass:
  style: compressed

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - jekyll-rtd-theme.gemspec
